export const menu = [
  {
    id: 'beverages',
    title: { en: 'Beverages', fr: 'Beverages' },
    items: [
      {
        id: '20oz-milkshakes',
        title: { en: '20oz Milkshakes', fr: '20oz Milkshakes' },
        body: { en: 'Chocolate, Strawberry, Vanilla, Creamsicle, Banana & Chocolate, Chocolate & PB, PB & J, Oreo, Smarties, Mochaccino, Coconut', fr: 'Chocolate, Strawberry, Vanilla, Creamsicle, Banana & Chocolate, Chocolate & PB, PB & J, Oreo, Smarties, Mochaccino, Coconut' },
        price: '$9.99',
      },
      {
        id: 'bottomless-pop',
        title: { en: 'Bottomless Pop', fr: 'Bottomless Pop' },
        body: { en: '', fr: '' },
        price: '$4.20',
      },
      {
        id: '14oz-tropicana-juice-or-milk',
        title: { en: '14oz Tropicana Juice or Milk', fr: '14oz Tropicana Juice or Milk' },
        body: { en: '', fr: '' },
        price: '$4.20',
      },
      {
        id: 'fizzybubbly',
        title: { en: 'Fizzybubbly', fr: 'Fizzybubbly' },
        body: { en: 'OJ & Sodawater', fr: 'OJ & Sodawater' },
        price: '$4.20',
      },
      {
        id: 'fresh-fruit-smoothie',
        title: { en: 'Fresh Fruit Smoothie', fr: 'Fresh Fruit Smoothie' },
        body: { en: '', fr: '' },
        price: '$8.99',
      },
      {
        id: 'coffee',
        title: { en: 'Coffee', fr: 'Coffee' },
        body: { en: 'Refillable', fr: 'Refillable' },
        price: '$3.49',
      },
      {
        id: 'americano',
        title: { en: 'Americano', fr: 'Americano' },
        body: { en: '', fr: '' },
        price: '$3.99',
      },
      {
        id: 'espresso',
        title: { en: 'Espresso', fr: 'Espresso' },
        body: { en: 'Double Espresso $4.49', fr: 'Double Espresso $4.49' },
        price: '$3.99',
      },
      {
        id: 'latte-bowl',
        title: { en: 'Latte Bowl', fr: 'Latte Bowl' },
        body: { en: 'Standard Size Latte $5.99 Make it Vanilla for $1 more', fr: 'Standard Size Latte $5.99 Make it Vanilla for $1 more' },
        price: '$8.49',
      },
      {
        id: 'diner-hot-chocolate',
        title: { en: 'Diner Hot Chocolate', fr: 'Diner Hot Chocolate' },
        body: { en: '', fr: '' },
        price: '$7.49',
      },
      {
        id: 'root-beer-float',
        title: { en: 'Root Beer Float', fr: 'Root Beer Float' },
        body: { en: 'A classic - Root beer with a scoop of vanilla ice cream for a creamy sweet twist', fr: 'A classic - Root beer with a scoop of vanilla ice cream for a creamy sweet twist' },
        price: '$6.99',
      },
      {
        id: 'mocha-bowl',
        title: { en: 'Mocha Bowl', fr: 'Mocha Bowl' },
        body: { en: 'Mocha cup $6.99', fr: 'Mocha cup $6.99' },
        price: '$9.49',
      },
    ],
  },
  {
    id: 'get-boozy',
    title: { en: 'Get Boozy', fr: 'Get Boozy' },
    items: [
      {
        id: 'diner-caesar',
        title: { en: 'Diner Caesar', fr: 'Diner Caesar' },
        body: { en: 'Classic Clamato, Vodka (1oz), Tabasco, Worcestershire, pickle juice, horseradish, & a dill pickle garnish. Get 2 for $15.99! Virgin Caesar $4.99', fr: 'Classic Clamato, Vodka (1oz), Tabasco, Worcestershire, pickle juice, horseradish, & a dill pickle garnish. Get 2 for $15.99! Virgin Caesar $4.99' },
        price: '$9.99',
      },
      {
        id: 'mimosas',
        title: { en: 'Mimosas', fr: 'Mimosas' },
        body: { en: 'Ask your server about juice options. Get 2 for $14.99!', fr: 'Ask your server about juice options. Get 2 for $14.99!' },
        price: '$8.99',
      },
      {
        id: 'diner-margarita',
        title: { en: 'Diner Margarita', fr: 'Diner Margarita' },
        body: { en: '2 oz Margarita', fr: '2 oz Margarita' },
        price: '$10.99',
      },
      {
        id: 'tequila-sunrise',
        title: { en: 'Tequila Sunrise', fr: 'Tequila Sunrise' },
        body: { en: 'Oj with grenadine unmixed, & of course Tequila (1oz), served with a salt rim.', fr: 'Oj with grenadine unmixed, & of course Tequila (1oz), served with a salt rim.' },
        price: '$9.99',
      },
      {
        id: 'beach-bum',
        title: { en: 'Beach Bum', fr: 'Beach Bum' },
        body: { en: 'Pineapple juice & Malibu Rum (1oz), served with a salt rim.', fr: 'Pineapple juice & Malibu Rum (1oz), served with a salt rim.' },
        price: '$9.99',
      },
      {
        id: 'greyhound',
        title: { en: 'Greyhound', fr: 'Greyhound' },
        body: { en: 'Grapefruit juice & Vodka (1oz), served with a sugar rim.', fr: 'Grapefruit juice & Vodka (1oz), served with a sugar rim.' },
        price: '$9.99',
      },
      {
        id: 'screwdriver',
        title: { en: 'Screwdriver', fr: 'Screwdriver' },
        body: { en: 'OJ & Vodka (1oz), served with a sugar rim.', fr: 'OJ & Vodka (1oz), served with a sugar rim.' },
        price: '$9.99',
      },
      {
        id: 'seabreeze',
        title: { en: 'Seabreeze', fr: 'Seabreeze' },
        body: { en: 'Cranberry & grapefruit juice with Vodka (1oz), served with a salt rim.', fr: 'Cranberry & grapefruit juice with Vodka (1oz), served with a salt rim.' },
        price: '$9.99',
      },
      {
        id: 'house-cabernet',
        title: { en: 'House Cabernet', fr: 'House Cabernet' },
        body: { en: '1/2 Litre $17.00 Litre $27.99', fr: '1/2 Litre $17.00 Litre $27.99' },
        price: '$8.99',
      },
      {
        id: 'house-pinot-grigio',
        title: { en: 'House Pinot Grigio', fr: 'House Pinot Grigio' },
        body: { en: '1/2 Litre $17.00 Litre $27.99', fr: '1/2 Litre $17.00 Litre $27.99' },
        price: '$8.99',
      },
      {
        id: 'beau-s-lugtread-largered-ale',
        title: { en: 'Beau\'s Lugtread Largered Ale', fr: 'Beau\'s Lugtread Largered Ale' },
        body: { en: 'Taste: A Graham cracker malt character mingles with notes of freshly cut hay and a subtle touch of apple. Sweet, grainy malt is followed by balanced hop bitterness, finish is clean and dry. Large ABV 5.2% Small: $5.99', fr: 'Taste: A Graham cracker malt character mingles with notes of freshly cut hay and a subtle touch of apple. Sweet, grainy malt is followed by balanced hop bitterness, finish is clean and dry. Large ABV 5.2% Small: $5.99' },
        price: '$9.99',
      },
      {
        id: 'beyond-the-pale-pink-fuzz',
        title: { en: 'Beyond The Pale - Pink Fuzz', fr: 'Beyond The Pale - Pink Fuzz' },
        body: { en: 'Wheat beer, hoppy with grapefruit notes. Large 6% Small: $5.99', fr: 'Wheat beer, hoppy with grapefruit notes. Large 6% Small: $5.99' },
        price: '$9.99',
      },
      {
        id: 'overflow-brewing-co-citrus-cerveza',
        title: { en: 'Overflow Brewing Co. - Citrus Cerveza', fr: 'Overflow Brewing Co. - Citrus Cerveza' },
        body: { en: 'Taste: Crisp and refreshing, tangy lemon and bright lime flavours with a subtle hint of briny Vancouver Island sea salt to add a nuanced complexity. Light and lively mouthfeel with a crisp dry finish. ABV: 4.5% IBU: 14 Small $5.99', fr: 'Taste: Crisp and refreshing, tangy lemon and bright lime flavours with a subtle hint of briny Vancouver Island sea salt to add a nuanced complexity. Light and lively mouthfeel with a crisp dry finish. ABV: 4.5% IBU: 14 Small $5.99' },
        price: '$9.99',
      },
      {
        id: 'draft-pitcher',
        title: { en: 'Draft Pitcher', fr: 'Draft Pitcher' },
        body: { en: '', fr: '' },
        price: '$21.99',
      },
    ],
  },
  {
    id: 'weekly-specials',
    title: { en: 'Weekly Specials', fr: 'Weekly Specials' },
    items: [
      {
        id: 'monday-kids-eat-free',
        title: { en: 'Monday Kids Eat Free', fr: 'Monday Kids Eat Free' },
        body: {
          en: 'After 4pm with the purchase of an adult meal & beverage. Coffee & Tea excluded. *** In-house only.',
          fr: 'After 4pm with the purchase of an adult meal & beverage. Coffee & Tea excluded. *** In-house only.',
        },
        price: null,
      },
      {
        id: 'tuesday-2-for-1-sundaes',
        title: { en: 'Tuesday 2 for 1 Sundaes', fr: 'Tuesday 2 for 1 Sundaes' },
        body: {
          en: '2 Sundaes for the price of 1 after 4pm. *** In-house only.',
          fr: '2 Sundaes for the price of 1 after 4pm. *** In-house only.',
        },
        price: null,
      },
      {
        id: 'sunday-buy-1-mac-get-1-half-off',
        title: { en: 'Sunday Buy 1 Mac Get 1 Half Off', fr: 'Sunday Buy 1 Mac Get 1 Half Off' },
        body: {
          en: 'Sunday after 4pm purchase 1 Mac & Cheese, get the second half off! With the purchase of a beverage. Coffee & Tea excluded. *** In-house only.',
          fr: 'Sunday after 4pm purchase 1 Mac & Cheese, get the second half off! With the purchase of a beverage. Coffee & Tea excluded. *** In-house only.',
        },
        price: null,
      },
      {
        id: 'early-bird-special',
        title: { en: 'Early Bird Special (Mon-Fri 8 - 10am)', fr: 'Early Bird Special (Mon-Fri 8 - 10am)' },
        body: {
          en: 'Traditional Breakfast, for the early birds (Monday - Friday Open till 10 am) 2 Eggs, & a choice of 3 slices of bacon, ham, or sausage. Served with seasoned homies & an order of toast. Coffee included. *Substitute your eggs or meat for: Smoked meat, pea meal bacon or 2 mini stoner sausages for an addition $3.99*',
          fr: 'Traditional Breakfast, for the early birds (Monday - Friday Open till 10 am) 2 Eggs, & a choice of 3 slices of bacon, ham, or sausage. Served with seasoned homies & an order of toast. Coffee included. *Substitute your eggs or meat for: Smoked meat, pea meal bacon or 2 mini stoner sausages for an addition $3.99*',
        },
        price: '$15.99',
      },
      {
        id: 'lunchbox-special',
        title: { en: 'Lunchbox Special (Mon-Fri 11am-2pm)', fr: 'Lunchbox Special (Mon-Fri 11am-2pm)' },
        body: {
          en: "Forgot your sammie at home? We've got it covered from 11am - 2pm get the soup and sandwich of the day for $15.99 with your choice of bread (white, brown, rye+0.75 $*)",
          fr: "Forgot your sammie at home? We've got it covered from 11am - 2pm get the soup and sandwich of the day for $15.99 with your choice of bread (white, brown, rye+0.75 $*)",
        },
        price: '$15.99',
      },
      {
        id: 'sundown-special',
        title: { en: 'Sundown Special', fr: 'Sundown Special' },
        body: {
          en: 'Buy 1 Burger with side an get a large beer for $5.99 *Monday - Friday after 4 pm*',
          fr: 'Buy 1 Burger with side an get a large beer for $5.99 *Monday - Friday after 4 pm*',
        },
        price: null,
      },
      {
        id: 'burger-buds',
        title: { en: 'Burger Buds', fr: 'Burger Buds' },
        body: {
          en: 'Buy 1 Burger at regular price and get the 2nd 50% off with an order of 2 drinks, excluding coffee and tea *Monday - Friday after 4pm*',
          fr: 'Buy 1 Burger at regular price and get the 2nd 50% off with an order of 2 drinks, excluding coffee and tea *Monday - Friday after 4pm*',
        },
        price: null,
      },
      {
        id: 'mac-daddy-food-challenge',
        title: { en: 'Mac Daddy Food Challenge', fr: 'Mac Daddy Food Challenge' },
        body: {
          en: 'Brought to you by The Wellington Diner, Made famous by the one and only Beard Meets Food. Now includes: Oreo Milkshake, Three Mac Daddy Burgers (two 6oz patties), and a Double Homie Poutine. Complete it in 40 minutes and the meals on us and you join this Legend! Rules: No leaving the table, no splitting, no take home or sharing. Finish it in 40 mins to win.',
          fr: 'Brought to you by The Wellington Diner, Made famous by the one and only Beard Meets Food. Now includes: Oreo Milkshake, Three Mac Daddy Burgers (two 6oz patties), and a Double Homie Poutine. Complete it in 40 minutes and the meals on us and you join this Legend! Rules: No leaving the table, no splitting, no take home or sharing. Finish it in 40 mins to win.',
        },
        price: '$49.99',
      },
    ],
  },
  {
    id: 'eggs-benny',
    title: { en: 'Eggs Benny', fr: 'Eggs Benny' },
    note: { en: 'Eggs Benny come POACHED or POACHED HARD at request. Two poached eggs atop an english muffin & smothered in savoury hollandaise. Served alongside house homies or a house salad. *Add sautéed onions to your homies for no additional cost*', fr: 'Eggs Benny come POACHED or POACHED HARD at request. Two poached eggs atop an english muffin & smothered in savoury hollandaise. Served alongside house homies or a house salad. *Add sautéed onions to your homies for no additional cost*' },
    items: [
      {
        id: 'the-wellington-benny',
        title: { en: 'The Wellington Benny', fr: 'The Wellington Benny' },
        body: { en: 'Thin sliced seasoned steak & caramelized onions.', fr: 'Thin sliced seasoned steak & caramelized onions.' },
        price: '$19.99',
      },
      {
        id: 'the-classic-benny',
        title: { en: 'The Classic Benny', fr: 'The Classic Benny' },
        body: { en: 'A Canadian favourite with grilled peameal.', fr: 'A Canadian favourite with grilled peameal.' },
        price: '$18.99',
      },
      {
        id: 'the-california-kid-benny',
        title: { en: 'The California Kid Benny', fr: 'The California Kid Benny' },
        body: { en: 'Grilled ham, guacamole, our 3-cheese blend & topped with chipotle hollandaise.', fr: 'Grilled ham, guacamole, our 3-cheese blend & topped with chipotle hollandaise.' },
        price: '$18.99',
      },
      {
        id: 'the-diner-florentine',
        title: { en: 'The Diner Florentine', fr: 'The Diner Florentine' },
        body: { en: 'Fresh baby spinach & a 3-cheese blend.', fr: 'Fresh baby spinach & a 3-cheese blend.' },
        price: '$17.99',
      },
      {
        id: 'bacon-grilled-cheese-benny',
        title: { en: 'Bacon Grilled Cheese Benny', fr: 'Bacon Grilled Cheese Benny' },
        body: { en: 'A bacon grilled cheese sammie topped with 2 poached eggs & smothered in savoury hollandaise sauce.', fr: 'A bacon grilled cheese sammie topped with 2 poached eggs & smothered in savoury hollandaise sauce.' },
        price: '$18.99',
      },
      {
        id: 'smoked-meat-benny',
        title: { en: 'Smoked Meat Benny', fr: 'Smoked Meat Benny' },
        body: { en: '5 oz Montreal style smoked meat & swiss cheese.', fr: '5 oz Montreal style smoked meat & swiss cheese.' },
        price: '$18.99',
      },
      {
        id: 'swipe-right-benny',
        title: { en: 'Swipe Right Benny', fr: 'Swipe Right Benny' },
        body: { en: 'Inside out grilled cheese sammie filled with pulled pork, two poached eggs, guacamole, topped with chipotle hollandaise.', fr: 'Inside out grilled cheese sammie filled with pulled pork, two poached eggs, guacamole, topped with chipotle hollandaise.' },
        price: '$21.49',
      },
      {
        id: 'miss-vicky',
        title: { en: 'Miss Vicky', fr: 'Miss Vicky' },
        body: { en: 'Sauted mixed peppers, onions, mushrooms, baby spinach, tomatoes.', fr: 'Sauted mixed peppers, onions, mushrooms, baby spinach, tomatoes.' },
        price: '$18.49',
      },
      {
        id: 'lady-natasha',
        title: { en: 'Lady Natasha', fr: 'Lady Natasha' },
        body: { en: 'Smoked Atlantic salmon, cream cheese spread, and baby spinach.', fr: 'Smoked Atlantic salmon, cream cheese spread, and baby spinach.' },
        price: '$21.99',
      },
      {
        id: 'east-coast-shuffle',
        title: { en: 'East Coast Shuffle', fr: 'East Coast Shuffle' },
        body: { en: 'Seasoned lobster, guacamole, sliced tomato, topped with savory hollandaise and bacon crumble.', fr: 'Seasoned lobster, guacamole, sliced tomato, topped with savory hollandaise and bacon crumble.' },
        price: '$19.99',
      },
    ],
  },
  {
    id: 'eggs-things',
    title: { en: 'Eggs & Things', fr: 'Eggs & Things' },
    note: { en: 'Served with seasoned homies & an order of toast. Coffee included. *Upgrade to: Rye Toast $0.75, Gluten free toast $1.99 *Add sautéed onions to your homies for no additional cost* *Substitute your eggs or meat for: Smoked meat, pea meal bacon or 2 mini stoner patties for an addition $3.99* **Poached eggs available as POACHED MEDIUM or POACHED HARD.**', fr: 'Served with seasoned homies & an order of toast. Coffee included. *Upgrade to: Rye Toast $0.75, Gluten free toast $1.99 *Add sautéed onions to your homies for no additional cost* *Substitute your eggs or meat for: Smoked meat, pea meal bacon or 2 mini stoner patties for an addition $3.99* **Poached eggs available as POACHED MEDIUM or POACHED HARD.**' },
    items: [
      {
        id: 'the-one-hit-wonder',
        title: { en: 'The One Hit Wonder', fr: 'The One Hit Wonder' },
        body: { en: '1 Egg, 2 slices of bacon, ham or sausage.', fr: '1 Egg, 2 slices of bacon, ham or sausage.' },
        price: '$15.99',
      },
      {
        id: 'traditional-breakfast',
        title: { en: 'Traditional Breakfast', fr: 'Traditional Breakfast' },
        body: { en: '2 Eggs, & a choice of 3 slices of bacon, ham, or sausage.', fr: '2 Eggs, & a choice of 3 slices of bacon, ham, or sausage.' },
        price: '$17.99',
      },
      {
        id: 'the-quebecer',
        title: { en: 'The Quebecer', fr: 'The Quebecer' },
        body: { en: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage, served up with a side of pork beans.', fr: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage, served up with a side of pork beans.' },
        price: '$18.99',
      },
      {
        id: 'the-biggie-breakfast',
        title: { en: 'The Biggie Breakfast', fr: 'The Biggie Breakfast' },
        body: { en: 'A plate for the hungry or hungover with 3 eggs, & an order of 3 bacon, 3 ham, & 3 sausages.', fr: 'A plate for the hungry or hungover with 3 eggs, & an order of 3 bacon, 3 ham, & 3 sausages.' },
        price: '$19.79',
      },
      {
        id: 'steak-eggs',
        title: { en: 'Steak & Eggs', fr: 'Steak & Eggs' },
        body: { en: '2 Eggs served alongside an 8oz AAA hand cut sirloin steak.', fr: '2 Eggs served alongside an 8oz AAA hand cut sirloin steak.' },
        price: '$20.99',
      },
      {
        id: 'the-bonanza',
        title: { en: 'The Bonanza', fr: 'The Bonanza' },
        body: { en: '3 Eggs, an 8oz AAA hand cut sirloin steak, bacon, ham, sausage, pork beans. Served with house homies and 3 slices of toast. **** Sharing fee of $4.99', fr: '3 Eggs, an 8oz AAA hand cut sirloin steak, bacon, ham, sausage, pork beans. Served with house homies and 3 slices of toast. **** Sharing fee of $4.99' },
        price: '$24.49',
      },
      {
        id: 'the-valley-pancake-breakfast',
        title: { en: 'The Valley Pancake Breakfast', fr: 'The Valley Pancake Breakfast' },
        body: { en: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage. Served with a real buttermilk pancake. Add Blueberries or Chocolate Chips for $1', fr: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage. Served with a real buttermilk pancake. Add Blueberries or Chocolate Chips for $1' },
        price: '$18.99',
      },
      {
        id: 'valley-french-toast',
        title: { en: 'Valley French Toast', fr: 'Valley French Toast' },
        body: { en: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage. Served with 1 slice of Brioche French toast.', fr: '2 Eggs, a choice of 3 pieces of bacon, ham, or sausage. Served with 1 slice of Brioche French toast.' },
        price: '$18.49',
      },
    ],
  },
  {
    id: 'scrambles-omelettes',
    title: { en: 'Scrambles & Omelettes', fr: 'Scrambles & Omelettes' },
    note: { en: 'Each made with 3 eggs and stuffed with an abundance of fresh ingredients. Served with your choice of toast & house homies, or a garden salad. *Add sautéed onions to your homies for no additional cost*', fr: 'Each made with 3 eggs and stuffed with an abundance of fresh ingredients. Served with your choice of toast & house homies, or a garden salad. *Add sautéed onions to your homies for no additional cost*' },
    items: [
      {
        id: 'the-1-omelette',
        title: { en: 'The #1 Omelette', fr: 'The #1 Omelette' },
        body: { en: 'Fresh baby spinach, mushrooms, loaded with creamy brie cheese.', fr: 'Fresh baby spinach, mushrooms, loaded with creamy brie cheese.' },
        price: '$18.99',
      },
      {
        id: 'western-omelette',
        title: { en: 'Western Omelette', fr: 'Western Omelette' },
        body: { en: 'Mixed peppers, onions, diced ham.', fr: 'Mixed peppers, onions, diced ham.' },
        price: '$17.99',
      },
      {
        id: 'cowboy-omelette',
        title: { en: 'Cowboy Omelette', fr: 'Cowboy Omelette' },
        body: { en: 'Pulled pork with smokey BBQ sauce, mixed peppers, onions, and a 3-cheese blend.', fr: 'Pulled pork with smokey BBQ sauce, mixed peppers, onions, and a 3-cheese blend.' },
        price: '$19.29',
      },
      {
        id: 'veggie-scramble',
        title: { en: 'Veggie Scramble', fr: 'Veggie Scramble' },
        body: { en: '3 Egg scramble with mixed peppers, onions, mushrooms, baby spinach, tomatoes, feta cheese.', fr: '3 Egg scramble with mixed peppers, onions, mushrooms, baby spinach, tomatoes, feta cheese.' },
        price: '$17.99',
      },
      {
        id: 'the-mish-mash-scramble',
        title: { en: 'The Mish Mash Scramble', fr: 'The Mish Mash Scramble' },
        body: { en: '3 Egg scramble with bacon, ham, sausage, sauteed mixed peppers & onions. Topped with a broiled 3 cheese blend. The cheese man, get it for the cheese!', fr: '3 Egg scramble with bacon, ham, sausage, sauteed mixed peppers & onions. Topped with a broiled 3 cheese blend. The cheese man, get it for the cheese!' },
        price: '$18.99',
      },
    ],
  },
  {
    id: 'our-breakfast-poutines-hashes',
    title: { en: 'Our Breakfast Poutines & Hashes', fr: 'Our Breakfast Poutines & Hashes' },
    note: { en: 'Big bowl of house homies, a variety of ingredients, & topped with signature hollandaise.', fr: 'Big bowl of house homies, a variety of ingredients, & topped with signature hollandaise.' },
    items: [
      {
        id: 'stoner-hash',
        title: { en: 'Stoner Hash', fr: 'Stoner Hash' },
        body: { en: 'In house sweet sausage stoner patty sauteed with bacon, mixed peppers, onions, a 3 cheese blend, 2 over-easy eggs, & a dose of chipotle hollandaise.', fr: 'In house sweet sausage stoner patty sauteed with bacon, mixed peppers, onions, a 3 cheese blend, 2 over-easy eggs, & a dose of chipotle hollandaise.' },
        price: '$18.99',
      },
      {
        id: 'mexican-hash',
        title: { en: 'Mexican Hash', fr: 'Mexican Hash' },
        body: { en: 'Ground chorizo sausage, sauteed mixed peppers and onions, mixed cheese, 2 over-easy eggs, guacamole, topped with chipotle hollandaise on a bed of homies.', fr: 'Ground chorizo sausage, sauteed mixed peppers and onions, mixed cheese, 2 over-easy eggs, guacamole, topped with chipotle hollandaise on a bed of homies.' },
        price: '$18.99',
      },
      {
        id: 'buddha-hash',
        title: { en: 'Buddha Hash', fr: 'Buddha Hash' },
        body: { en: 'Fresh baby spinach, mixed peppers & onions, tomatoes, mushrooms, 2 over-easy eggs, pesto hollandaise, and feta cheese on a bed of homies.', fr: 'Fresh baby spinach, mixed peppers & onions, tomatoes, mushrooms, 2 over-easy eggs, pesto hollandaise, and feta cheese on a bed of homies.' },
        price: '$18.99',
      },
      {
        id: 'smoked-meat-hash',
        title: { en: 'Smoked Meat Hash', fr: 'Smoked Meat Hash' },
        body: { en: 'Juicy smoked meat, sauteed peppers & onions, 3 cheese blend with 2 over-easy eggs, & chipotle hollandaise.', fr: 'Juicy smoked meat, sauteed peppers & onions, 3 cheese blend with 2 over-easy eggs, & chipotle hollandaise.' },
        price: '$18.99',
      },
      {
        id: 'carnivore-poutine',
        title: { en: 'Carnivore Poutine', fr: 'Carnivore Poutine' },
        body: { en: 'Bacon, sausage, & ham, loaded with St. Albert\'s cheese curds & topped with savoury hollandaise.', fr: 'Bacon, sausage, & ham, loaded with St. Albert\'s cheese curds & topped with savoury hollandaise.' },
        price: '$17.29',
      },
      {
        id: 'homie-breakfast-poutine',
        title: { en: 'Homie Breakfast Poutine', fr: 'Homie Breakfast Poutine' },
        body: { en: 'Loads of St. Albert\'s cheese curds smothered in savoury hollandaise. Try it with bacon or sausage for $2.99!', fr: 'Loads of St. Albert\'s cheese curds smothered in savoury hollandaise. Try it with bacon or sausage for $2.99!' },
        price: '$12.99',
      },
      {
        id: '6-shooter-hash',
        title: { en: '6 Shooter Hash', fr: '6 Shooter Hash' },
        body: { en: '6oz Pulled pork, mixed peppers, onions, 3-cheese blend, 2 over-easy eggs, chipotle hollandaise, guacamole.', fr: '6oz Pulled pork, mixed peppers, onions, 3-cheese blend, 2 over-easy eggs, chipotle hollandaise, guacamole.' },
        price: '$19.99',
      },
      {
        id: 'alpha-bowl',
        title: { en: 'Alpha Bowl', fr: 'Alpha Bowl' },
        body: { en: 'Seasoned steak, mixed peppers, onions, 3 cheese blend, 2 over-easy eggs, topped with chipotle hollandaise and guacamole.', fr: 'Seasoned steak, mixed peppers, onions, 3 cheese blend, 2 over-easy eggs, topped with chipotle hollandaise and guacamole.' },
        price: '$19.99',
      },
    ],
  },
  {
    id: 'light-healthy',
    title: { en: 'Light & Healthy', fr: 'Light & Healthy' },
    note: { en: 'A collection of lighter dishes to fuel your day.', fr: 'A collection of lighter dishes to fuel your day.' },
    items: [
      {
        id: 'fresh-start',
        title: { en: 'Fresh Start', fr: 'Fresh Start' },
        body: { en: '2 Poached eggs served with a sesame seed bagel, cream cheese, and a fruit bowl. *** This item does not include homies.', fr: '2 Poached eggs served with a sesame seed bagel, cream cheese, and a fruit bowl. *** This item does not include homies.' },
        price: '$16.99',
      },
      {
        id: 'the-greek-breakfast',
        title: { en: 'The Greek Breakfast', fr: 'The Greek Breakfast' },
        body: { en: '2 Eggs served with 5 slices of cucumber, 5 slices of tomato, crumbled feta, and olives on top. Served with an order of toast. * This item does not include a side of homie fries, they are available for $4.20.', fr: '2 Eggs served with 5 slices of cucumber, 5 slices of tomato, crumbled feta, and olives on top. Served with an order of toast. * This item does not include a side of homie fries, they are available for $4.20.' },
        price: '$16.99',
      },
      {
        id: 'smoked-salmon-platter',
        title: { en: 'Smoked Salmon Platter', fr: 'Smoked Salmon Platter' },
        body: { en: 'Smoked Atlantic Salmon topped with capers & onions. Served with a sesame seed bagel, cream cheese, lemon, and a house salad.', fr: 'Smoked Atlantic Salmon topped with capers & onions. Served with a sesame seed bagel, cream cheese, lemon, and a house salad.' },
        price: '$21.99',
      },
      {
        id: 'oatmeal',
        title: { en: 'Oatmeal', fr: 'Oatmeal' },
        body: { en: 'A full bowl made fresh to order and served with a side of brown sugar and steamed milk. Add seasonal berries for $3.99', fr: 'A full bowl made fresh to order and served with a side of brown sugar and steamed milk. Add seasonal berries for $3.99' },
        price: '$11.29',
      },
      {
        id: 'bagel-n-cream-cheese',
        title: { en: 'Bagel \'N\' Cream Cheese', fr: 'Bagel \'N\' Cream Cheese' },
        body: { en: 'Sesame seed bagel loaded with cream cheese, served with coleslaw and pickle.', fr: 'Sesame seed bagel loaded with cream cheese, served with coleslaw and pickle.' },
        price: '$6.99',
      },
      {
        id: 'cobb-salad',
        title: { en: 'Cobb Salad', fr: 'Cobb Salad' },
        body: { en: 'Grilled chicken breast, guacamole, bacon, a hard boiled egg, cucumbers, tomatoes, carrots, red cabbage & 3 cheese-blend on a bed of mixed greens. Served with Blue Cheese dressing.', fr: 'Grilled chicken breast, guacamole, bacon, a hard boiled egg, cucumbers, tomatoes, carrots, red cabbage & 3 cheese-blend on a bed of mixed greens. Served with Blue Cheese dressing.' },
        price: '$19.49',
      },
      {
        id: 'diner-caesar-salad',
        title: { en: 'Diner Caesar Salad', fr: 'Diner Caesar Salad' },
        body: { en: 'Leafy greens, shredded Parmesan, handmade croutons, & fresh bacon bits all tossed in creamy garlic Caesar dressing. Add Chicken $4.99', fr: 'Leafy greens, shredded Parmesan, handmade croutons, & fresh bacon bits all tossed in creamy garlic Caesar dressing. Add Chicken $4.99' },
        price: '$16.99',
      },
      {
        id: 'greek-salad',
        title: { en: 'Greek Salad', fr: 'Greek Salad' },
        body: { en: 'Mixed greens, cucumber, tomato, red cabbage, carrots, feta cheese & olives.', fr: 'Mixed greens, cucumber, tomato, red cabbage, carrots, feta cheese & olives.' },
        price: '$16.49',
      },
      {
        id: 'house-salad',
        title: { en: 'House Salad', fr: 'House Salad' },
        body: { en: 'Mixed greens, cucumber, tomato, red cabbage & carrots, with your choice of dressing.', fr: 'Mixed greens, cucumber, tomato, red cabbage & carrots, with your choice of dressing.' },
        price: '$15.29',
      },
    ],
  },
  {
    id: 'breakfast-clubs-wraps',
    title: { en: 'Breakfast Clubs & Wraps', fr: 'Breakfast Clubs & Wraps' },
    note: { en: 'Sure to satisfy, our triple deckers are served with house homies or garden salad. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99', fr: 'Sure to satisfy, our triple deckers are served with house homies or garden salad. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99' },
    items: [
      {
        id: 'the-breakfast-club',
        title: { en: 'The Breakfast Club', fr: 'The Breakfast Club' },
        body: { en: '2 Over-medium eggs, bacon, cheddar cheese, lettuce, tomato, mayo.', fr: '2 Over-medium eggs, bacon, cheddar cheese, lettuce, tomato, mayo.' },
        price: '$18.99',
      },
      {
        id: 'breakfast-burrito',
        title: { en: 'Breakfast Burrito', fr: 'Breakfast Burrito' },
        body: { en: '3 Scrambled eggs, chorizo sausage, sautéed peppers, onions, guacamole, cheddar cheese, and juicy salsa.', fr: '3 Scrambled eggs, chorizo sausage, sautéed peppers, onions, guacamole, cheddar cheese, and juicy salsa.' },
        price: '$18.99',
      },
      {
        id: 'mother-clubber',
        title: { en: 'Mother Clubber', fr: 'Mother Clubber' },
        body: { en: '2 Over-medium eggs, guacamole, Monterey jack cheese, lettuce, tomato, mayo.', fr: '2 Over-medium eggs, guacamole, Monterey jack cheese, lettuce, tomato, mayo.' },
        price: '$18.99',
      },
      {
        id: 'the-stoner-burger',
        title: { en: 'The Stoner Burger', fr: 'The Stoner Burger' },
        body: { en: 'Sweet sausage patty, sunny side egg, bacon, cheddar cheese, chipotle mayo on a Brioche bun.', fr: 'Sweet sausage patty, sunny side egg, bacon, cheddar cheese, chipotle mayo on a Brioche bun.' },
        price: '$19.29',
      },
      {
        id: 'the-drake',
        title: { en: 'The Drake', fr: 'The Drake' },
        body: { en: 'Breakfast wrap filled with 3 eggs, 5oz of Montreal style smoked meat, chipotle mayo, and cheese.', fr: 'Breakfast wrap filled with 3 eggs, 5oz of Montreal style smoked meat, chipotle mayo, and cheese.' },
        price: '$19.89',
      },
      {
        id: 'egg-mcdiner',
        title: { en: 'Egg McDiner', fr: 'Egg McDiner' },
        body: { en: '3 Scrambled eggs, melted cheddar, 3 strips of bacon OR stoner slider OR onion rings. Your choice of chipotle, pesto or regular mayo. Side included.', fr: '3 Scrambled eggs, melted cheddar, 3 strips of bacon OR stoner slider OR onion rings. Your choice of chipotle, pesto or regular mayo. Side included.' },
        price: '$17.99',
      },
    ],
  },
  {
    id: 'yummies',
    title: { en: 'Yummies', fr: 'Yummies' },
    note: { en: 'For the sweet tooth.', fr: 'For the sweet tooth.' },
    items: [
      {
        id: 'buttermilk-pancakes',
        title: { en: 'Buttermilk Pancakes', fr: 'Buttermilk Pancakes' },
        body: { en: '3 Tremendous country-kitchen style real buttermilk pancakes. Served with a topping of icing sugar & a side of whip cream.', fr: '3 Tremendous country-kitchen style real buttermilk pancakes. Served with a topping of icing sugar & a side of whip cream.' },
        price: '$17.99',
      },
      {
        id: 'chocolate-chip-or-blueberry-pancakes',
        title: { en: 'Chocolate Chip or Blueberry Pancakes', fr: 'Chocolate Chip or Blueberry Pancakes' },
        body: { en: '3 Tremendous country-kitchen style real buttermilk pancakes sprinkled with chocolate chips or blueberries. Topped with icing sugar & a side of whip cream.', fr: '3 Tremendous country-kitchen style real buttermilk pancakes sprinkled with chocolate chips or blueberries. Topped with icing sugar & a side of whip cream.' },
        price: '$18.99',
      },
      {
        id: 'single-pancake',
        title: { en: 'Single Pancake', fr: 'Single Pancake' },
        body: { en: 'Single buttermilk pancake. Chocolate or Blueberry +$1.00', fr: 'Single buttermilk pancake. Chocolate or Blueberry +$1.00' },
        price: '$7.99',
      },
      {
        id: 'french-toast',
        title: { en: 'French Toast', fr: 'French Toast' },
        body: { en: '3 Slices of Brioche bread served with a fruit salad, icing sugar, and whip cream.', fr: '3 Slices of Brioche bread served with a fruit salad, icing sugar, and whip cream.' },
        price: '$17.29',
      },
      {
        id: 'single-french-toast',
        title: { en: 'Single French Toast', fr: 'Single French Toast' },
        body: { en: 'Single Brioche French Toast.', fr: 'Single Brioche French Toast.' },
        price: '$7.99',
      },
    ],
  },
  {
    id: 'tasty-apps',
    title: { en: 'Tasty Apps', fr: 'Tasty Apps' },
    items: [
      {
        id: 'french-onion-soup',
        title: { en: 'French Onion Soup', fr: 'French Onion Soup' },
        body: { en: 'Delicious, French Onion Soup! Make it a large for +$2.00', fr: 'Delicious, French Onion Soup! Make it a large for +$2.00' },
        price: '$9.99',
      },
      {
        id: 'chili',
        title: { en: 'Chili', fr: 'Chili' },
        body: { en: 'Delicious, Chili! Make it a large for +$2.00', fr: 'Delicious, Chili! Make it a large for +$2.00' },
        price: '$9.99',
      },
      {
        id: 'home-fries',
        title: { en: 'Home Fries', fr: 'Home Fries' },
        body: { en: 'Cubed fries shaken in a breakfast mix.', fr: 'Cubed fries shaken in a breakfast mix.' },
        price: '$4.20',
      },
      {
        id: 'fries',
        title: { en: 'Fries', fr: 'Fries' },
        body: { en: 'Classic French fries', fr: 'Classic French fries' },
        price: '$4.20',
      },
      {
        id: 'onion-rings',
        title: { en: 'Onion Rings', fr: 'Onion Rings' },
        body: { en: 'Bowl of O-rings with plenty to share. Served with chipotle mayo.', fr: 'Bowl of O-rings with plenty to share. Served with chipotle mayo.' },
        price: '$9.29',
      },
      {
        id: 'jalapeno-poppers',
        title: { en: 'Jalapeno Poppers', fr: 'Jalapeno Poppers' },
        body: { en: '5 Breaded jalapenos stuffed with a cream cheese filling, served with a side salsa.', fr: '5 Breaded jalapenos stuffed with a cream cheese filling, served with a side salsa.' },
        price: '$10.49',
      },
      {
        id: 'deep-fried-pickles',
        title: { en: 'Deep Fried Pickles', fr: 'Deep Fried Pickles' },
        body: { en: '5 Flash-fried crispy, tangy dill pickles served with creamy ranch dressing.', fr: '5 Flash-fried crispy, tangy dill pickles served with creamy ranch dressing.' },
        price: '$9.99',
      },
      {
        id: 'mozzarella-sticks',
        title: { en: 'Mozzarella Sticks', fr: 'Mozzarella Sticks' },
        body: { en: '5 Thick mozzarella sticks with a double battered crisp shell. Served with a side salsa.', fr: '5 Thick mozzarella sticks with a double battered crisp shell. Served with a side salsa.' },
        price: '$10.29',
      },
    ],
  },
  {
    id: 'mains',
    title: { en: 'Mains', fr: 'Mains' },
    note: { en: 'Diner classics to satisfy the pickiest of eaters. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49', fr: 'Diner classics to satisfy the pickiest of eaters. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49' },
    items: [
      {
        id: 'fish-chips',
        title: { en: 'Fish & Chips', fr: 'Fish & Chips' },
        body: { en: 'Battered Haddock served with fresh fries, side peas, coleslaw, tangy pickles, tartar sauce, & lemon.', fr: 'Battered Haddock served with fresh fries, side peas, coleslaw, tangy pickles, tartar sauce, & lemon.' },
        price: '$18.99',
      },
      {
        id: 'salisbury-steak',
        title: { en: 'Salisbury Steak', fr: 'Salisbury Steak' },
        body: { en: 'Hamburger steak smothered in gravy & caramelized onions onions. Served with fries, side peas, coleslaw & tangy dill pickles. Add sauteed mushrooms for $1.29!', fr: 'Hamburger steak smothered in gravy & caramelized onions onions. Served with fries, side peas, coleslaw & tangy dill pickles. Add sauteed mushrooms for $1.29!' },
        price: '$18.99',
      },
      {
        id: 'hot-hamburger',
        title: { en: 'Hot Hamburger', fr: 'Hot Hamburger' },
        body: { en: 'Our classic patty stuffed between 2 slices of bread & smothered in house gravy. Served with fries, a side of peas, coleslaw, & a tangy dill pickle.', fr: 'Our classic patty stuffed between 2 slices of bread & smothered in house gravy. Served with fries, a side of peas, coleslaw, & a tangy dill pickle.' },
        price: '$18.99',
      },
      {
        id: 'hot-chicken-sandwich',
        title: { en: 'Hot Chicken Sandwich', fr: 'Hot Chicken Sandwich' },
        body: { en: 'Oven roasted chicken stuffed between 2 slices of bread & smothered in house beef gravy. Served with fries, a side of peas, coleslaw, & a tangy dill pickle.', fr: 'Oven roasted chicken stuffed between 2 slices of bread & smothered in house beef gravy. Served with fries, a side of peas, coleslaw, & a tangy dill pickle.' },
        price: '$18.99',
      },
      {
        id: 'steak-frites',
        title: { en: 'Steak Frites', fr: 'Steak Frites' },
        body: { en: '8oz Striploin with frites, caesar salad, and pesto mayo dip. Served with a side gravy dip, coleslaw, & a tangy dill pickle.', fr: '8oz Striploin with frites, caesar salad, and pesto mayo dip. Served with a side gravy dip, coleslaw, & a tangy dill pickle.' },
        price: '$22.99',
      },
      {
        id: 'chicken-finger-platter',
        title: { en: 'Chicken Finger Platter', fr: 'Chicken Finger Platter' },
        body: { en: '4 Juicy breaded chicken fingers. Served with fries, coleslaw, & tangy dill pickles. Feed your inner child.', fr: '4 Juicy breaded chicken fingers. Served with fries, coleslaw, & tangy dill pickles. Feed your inner child.' },
        price: '$18.99',
      },
      {
        id: 'buffalo-chicken-finger-platter',
        title: { en: 'Buffalo Chicken Finger Platter', fr: 'Buffalo Chicken Finger Platter' },
        body: { en: '4 Juicy breaded chicken fingers tossed in hot sauce. Served with fries, coleslaw, & tangy dill pickles. Served with side of Ranch', fr: '4 Juicy breaded chicken fingers tossed in hot sauce. Served with fries, coleslaw, & tangy dill pickles. Served with side of Ranch' },
        price: '$19.99',
      },
      {
        id: 'chicken-quesadilla',
        title: { en: 'Chicken Quesadilla', fr: 'Chicken Quesadilla' },
        body: { en: 'Oven-roasted chicken, 3 cheese blend, fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*', fr: 'Oven-roasted chicken, 3 cheese blend, fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*' },
        price: '$18.99',
      },
      {
        id: 'pulled-pork-quesadilla',
        title: { en: 'Pulled Pork Quesadilla', fr: 'Pulled Pork Quesadilla' },
        body: { en: 'Pulled Pork, 3 cheese blend, fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*', fr: 'Pulled Pork, 3 cheese blend, fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*' },
        price: '$18.99',
      },
      {
        id: 'steak-quesadilla',
        title: { en: 'Steak Quesadilla', fr: 'Steak Quesadilla' },
        body: { en: 'Seasoned steak, 3 cheese blend, fresh sauteed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*', fr: 'Seasoned steak, 3 cheese blend, fresh sauteed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*' },
        price: '$18.99',
      },
      {
        id: 'veggie-quesadilla',
        title: { en: 'Veggie Quesadilla', fr: 'Veggie Quesadilla' },
        body: { en: 'Fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*', fr: 'Fresh sautéed peppers and onions. Served with sour cream and salsa. *This item does not include a side.*' },
        price: '$18.99',
      },
    ],
  },
  {
    id: 'mac-n-cheese-house-specialty',
    title: { en: 'Mac \'N Cheese House Specialty', fr: 'Mac \'N Cheese House Specialty' },
    note: { en: 'Comfort food at it\'s finest, always cooked to order. Topped with Panko crumbs in a 4-cheese béchamel sauce. Served with a choice of fries or salad. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99', fr: 'Comfort food at it\'s finest, always cooked to order. Topped with Panko crumbs in a 4-cheese béchamel sauce. Served with a choice of fries or salad. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99' },
    items: [
      {
        id: 'mama-s-mac',
        title: { en: 'Mama\'s Mac', fr: 'Mama\'s Mac' },
        body: { en: 'Sweet cream, garlic, Parmesan. Try it with bacon! $2.49 Extra cheese for $2.20', fr: 'Sweet cream, garlic, Parmesan. Try it with bacon! $2.49 Extra cheese for $2.20' },
        price: '$18.49',
      },
      {
        id: 'carbonara-mac',
        title: { en: 'Carbonara Mac', fr: 'Carbonara Mac' },
        body: { en: 'A Mac & Cheese with a 4-cheese bechamel sauce, bacon crumbles, mushrooms, and caramelized onions. Add extra cheese $2.20.', fr: 'A Mac & Cheese with a 4-cheese bechamel sauce, bacon crumbles, mushrooms, and caramelized onions. Add extra cheese $2.20.' },
        price: '$19.99',
      },
      {
        id: 'lobster-mac',
        title: { en: 'Lobster Mac', fr: 'Lobster Mac' },
        body: { en: 'Seasoned lobster & a hint of garlic baked into a creamy bechamel sauce. Extra cheese for $2.20', fr: 'Seasoned lobster & a hint of garlic baked into a creamy bechamel sauce. Extra cheese for $2.20' },
        price: '$21.99',
      },
      {
        id: 'buffalo-chicken-mac',
        title: { en: 'Buffalo Chicken Mac', fr: 'Buffalo Chicken Mac' },
        body: { en: 'Crispy chicken, Franks Red Hot, creamy bechamel sauce, bacon bits. You could share but you won\'t want to. Extra cheese for $2.20', fr: 'Crispy chicken, Franks Red Hot, creamy bechamel sauce, bacon bits. You could share but you won\'t want to. Extra cheese for $2.20' },
        price: '$21.99',
      },
      {
        id: 'bbq-pulled-pork-mac',
        title: { en: 'BBQ Pulled Pork Mac', fr: 'BBQ Pulled Pork Mac' },
        body: { en: 'Slow-cooked pulled pork, sweet smokey house BBQ sauce. Add extra cheese $2.20.', fr: 'Slow-cooked pulled pork, sweet smokey house BBQ sauce. Add extra cheese $2.20.' },
        price: '$20.99',
      },
      {
        id: 'philly-steak-mac',
        title: { en: 'Philly Steak Mac', fr: 'Philly Steak Mac' },
        body: { en: 'Thinly sliced seasoned steak, mixed peppers, onions, mushrooms, garlic, with a tangy cream cheese sauce. Add extra cheese $2.20.', fr: 'Thinly sliced seasoned steak, mixed peppers, onions, mushrooms, garlic, with a tangy cream cheese sauce. Add extra cheese $2.20.' },
        price: '$21.99',
      },
      {
        id: 'pesto-chicken-mac',
        title: { en: 'Pesto Chicken Mac', fr: 'Pesto Chicken Mac' },
        body: { en: 'Fresh mixed peppers, onions, baby spinach and oven-roasted chicken in a creamy pesto bechamel sauce. Add extra cheese $2.20.', fr: 'Fresh mixed peppers, onions, baby spinach and oven-roasted chicken in a creamy pesto bechamel sauce. Add extra cheese $2.20.' },
        price: '$19.99',
      },
      {
        id: 'mama-s-maple-bacon-mac',
        title: { en: 'Mama\'s Maple Bacon Mac', fr: 'Mama\'s Maple Bacon Mac' },
        body: { en: 'Candied Bacon tossed in our Creamy Cheesy House Blend to make our Satisfying Mama\'s Maple Bacon Mac & Cheese', fr: 'Candied Bacon tossed in our Creamy Cheesy House Blend to make our Satisfying Mama\'s Maple Bacon Mac & Cheese' },
        price: '$19.99',
      },
    ],
  },
  {
    id: 'our-famous-poutines',
    title: { en: 'Our Famous Poutines', fr: 'Our Famous Poutines' },
    note: { en: 'Big hearty bowls loaded with St. Albert\'s cheese curds & smothered in beef gravy.', fr: 'Big hearty bowls loaded with St. Albert\'s cheese curds & smothered in beef gravy.' },
    items: [
      {
        id: 'classic-poutine',
        title: { en: 'Classic Poutine', fr: 'Classic Poutine' },
        body: { en: 'A bowl of fresh-cut fries & St. Albert\'s cheese curds smothered in gravy. Add extra curds for $2.49.', fr: 'A bowl of fresh-cut fries & St. Albert\'s cheese curds smothered in gravy. Add extra curds for $2.49.' },
        price: '$11.99',
      },
      {
        id: 'the-montrealer',
        title: { en: 'The Montrealer', fr: 'The Montrealer' },
        body: { en: 'Loads of juicy diced Montreal-style smoked meat. Add extra curds for $2.49!', fr: 'Loads of juicy diced Montreal-style smoked meat. Add extra curds for $2.49!' },
        price: '$18.99',
      },
      {
        id: 'piggy-s-poutine',
        title: { en: 'Piggy\'s Poutine', fr: 'Piggy\'s Poutine' },
        body: { en: 'Slow-roasted in-house pulled pork topped with caramelized onions. Add extra curds for $2.49!', fr: 'Slow-roasted in-house pulled pork topped with caramelized onions. Add extra curds for $2.49!' },
        price: '$18.99',
      },
      {
        id: 'wellington-poutine',
        title: { en: 'Wellington Poutine', fr: 'Wellington Poutine' },
        body: { en: 'Thinly sliced seasoned steak, mixed peppers, onions, & mushrooms all top a big bowl of fries & St. Albert cheese curds. Add extra curds for $2.49!', fr: 'Thinly sliced seasoned steak, mixed peppers, onions, & mushrooms all top a big bowl of fries & St. Albert cheese curds. Add extra curds for $2.49!' },
        price: '$18.99',
      },
      {
        id: 'the-pickler',
        title: { en: '★ The Pickler', fr: '★ The Pickler' },
        body: { en: 'Our classic poutine topped with chopped deep fried pickles, and a drizzle of Franks Red Hot and ranch. Strangely addictive.', fr: 'Our classic poutine topped with chopped deep fried pickles, and a drizzle of Franks Red Hot and ranch. Strangely addictive.' },
        price: '$17.99',
      },
    ],
  },
  {
    id: 'homemade-burger',
    title: { en: 'Homemade Burger', fr: 'Homemade Burger' },
    note: { en: 'House-made 6oz patties seasoned with secret diner seasoning. Served with fresh fries, house slaw & sliced dill pickle. Beyond Meat Patty available as a Veggie Patty. *Substitute your bun for gluten free toast for $1 more* Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49', fr: 'House-made 6oz patties seasoned with secret diner seasoning. Served with fresh fries, house slaw & sliced dill pickle. Beyond Meat Patty available as a Veggie Patty. *Substitute your bun for gluten free toast for $1 more* Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49' },
    items: [
      {
        id: 'the-hamburger',
        title: { en: 'The Hamburger', fr: 'The Hamburger' },
        body: { en: 'Single patty, grilled to perfection. Served with fresh lettuce & tomato. Add bacon or cheddar cheese for $1.49', fr: 'Single patty, grilled to perfection. Served with fresh lettuce & tomato. Add bacon or cheddar cheese for $1.49' },
        price: '$17.99',
      },
      {
        id: 'the-bacon-cheeseburger',
        title: { en: 'The Bacon Cheeseburger', fr: 'The Bacon Cheeseburger' },
        body: { en: 'House patty topped with cheddar cheese & crisp bacon. Served with fresh lettuce & tomato.', fr: 'House patty topped with cheddar cheese & crisp bacon. Served with fresh lettuce & tomato.' },
        price: '$18.99',
      },
      {
        id: 'the-baja',
        title: { en: 'The Baja', fr: 'The Baja' },
        body: { en: 'House patty, cream cheese, jalapenos, Franks Red Hot, bacon, lettuce, tomato.', fr: 'House patty, cream cheese, jalapenos, Franks Red Hot, bacon, lettuce, tomato.' },
        price: '$18.99',
      },
      {
        id: 'the-brie-burger',
        title: { en: 'The Brie Burger', fr: 'The Brie Burger' },
        body: { en: 'House patty, brie cheese, caramelized onions, sauteed mushrooms, lettuce, tomato.', fr: 'House patty, brie cheese, caramelized onions, sauteed mushrooms, lettuce, tomato.' },
        price: '$18.99',
      },
      {
        id: 'jr-mac-daddy',
        title: { en: 'Jr. Mac Daddy', fr: 'Jr. Mac Daddy' },
        body: { en: 'House patty, topped with fancy sauce, cheddar cheese, diced onions, pickles, shredded lettuce, & tomato.', fr: 'House patty, topped with fancy sauce, cheddar cheese, diced onions, pickles, shredded lettuce, & tomato.' },
        price: '$17.99',
      },
      {
        id: 'the-firecracker',
        title: { en: 'The Firecracker', fr: 'The Firecracker' },
        body: { en: 'House patty, 2 jalapeno poppers, cheddar cheese, fresh red peppers, & good old-fashioned onion rings. All dripping in chipotle mayo & Franks Red Hot.', fr: 'House patty, 2 jalapeno poppers, cheddar cheese, fresh red peppers, & good old-fashioned onion rings. All dripping in chipotle mayo & Franks Red Hot.' },
        price: '$19.49',
      },
      {
        id: 'the-kentucky-crunch',
        title: { en: 'The Kentucky Crunch', fr: 'The Kentucky Crunch' },
        body: { en: 'Crispy breaded chicken breast topped with homemade slaw, apple spears, crisp bacon, Monetary jack cheese & dripping with chipotle mayo.', fr: 'Crispy breaded chicken breast topped with homemade slaw, apple spears, crisp bacon, Monetary jack cheese & dripping with chipotle mayo.' },
        price: '$19.29',
      },
      {
        id: 'the-phat-ass-burger',
        title: { en: 'The Phat Ass Burger', fr: 'The Phat Ass Burger' },
        body: { en: 'You came here for a reason: this burger is it. Fresh patty stacked with house pulled-pork, 3 mozzarella sticks, mixed cheese, crisp bacon, & dripping with chipotle mayo.', fr: 'You came here for a reason: this burger is it. Fresh patty stacked with house pulled-pork, 3 mozzarella sticks, mixed cheese, crisp bacon, & dripping with chipotle mayo.' },
        price: '$20.99',
      },
      {
        id: 'double-grilled-cheese-burger',
        title: { en: 'Double Grilled Cheese Burger', fr: 'Double Grilled Cheese Burger' },
        body: { en: 'House burger patty stuffed between 2 grilled cheese sandwiches. Because why not? Available with bacon for an addition $2', fr: 'House burger patty stuffed between 2 grilled cheese sandwiches. Because why not? Available with bacon for an addition $2' },
        price: '$19.99',
      },
      {
        id: 'the-mac-daddy',
        title: { en: 'The Mac Daddy', fr: 'The Mac Daddy' },
        body: { en: '2 House patties, double cheddar cheese, diced onion, pickles, shredded lettuce, tomato, and fancy sauce.', fr: '2 House patties, double cheddar cheese, diced onion, pickles, shredded lettuce, tomato, and fancy sauce.' },
        price: '$21.99',
      },
      {
        id: 'chucky-cheese-burger',
        title: { en: 'Chucky Cheese Burger', fr: 'Chucky Cheese Burger' },
        body: { en: 'House patty with a gooey St. Alberts cheese curd skirt drapped over, topped with bacon.', fr: 'House patty with a gooey St. Alberts cheese curd skirt drapped over, topped with bacon.' },
        price: '$19.99',
      },
      {
        id: 'the-country-chicken',
        title: { en: 'The Country Chicken', fr: 'The Country Chicken' },
        body: { en: 'Crispy breaded chicken breast topped with Bacon, Monterey jack, lettuce, tomato, and mayo. ** Guacamole available as a substitute for bacon.', fr: 'Crispy breaded chicken breast topped with Bacon, Monterey jack, lettuce, tomato, and mayo. ** Guacamole available as a substitute for bacon.' },
        price: '$18.99',
      },
      {
        id: 'hot-sauce-josh',
        title: { en: 'Hot Sauce Josh', fr: 'Hot Sauce Josh' },
        body: { en: 'Crispy chicken breast with Monterey jack cheese, jalapenos, bacon, and Frank\'s Red Hot on brioche bun sauced with chipotle mayo and ranch dressing.', fr: 'Crispy chicken breast with Monterey jack cheese, jalapenos, bacon, and Frank\'s Red Hot on brioche bun sauced with chipotle mayo and ranch dressing.' },
        price: '$18.99',
      },
      {
        id: 'royale-burger',
        title: { en: 'Royale Burger', fr: 'Royale Burger' },
        body: { en: 'A brioche bun burger with bacon, cheese and smothered in gravy. side included.', fr: 'A brioche bun burger with bacon, cheese and smothered in gravy. side included.' },
        price: '$20.99',
      },
    ],
  },
  {
    id: 'our-signature-clubs-wraps',
    title: { en: 'Our Signature Clubs & Wraps', fr: 'Our Signature Clubs & Wraps' },
    note: { en: 'Fresh triple deckers served with house salad or fresh fries, homemade slaw, and dill pickles. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49', fr: 'Fresh triple deckers served with house salad or fresh fries, homemade slaw, and dill pickles. Side Upgrades: Onion Rings $4.20, Caesar Salad $4.49, Poutine $4.99, Homie Poutine $4.99, NEW - Side of Mac n Cheese $6.99 Try our specialty mayo: Pesto, Chipotle or Red Pepper for $1.49' },
    items: [
      {
        id: 'california-club',
        title: { en: 'California Club', fr: 'California Club' },
        body: { en: 'Oven-roasted chicken, guacamole, Monetary jack cheese, chipotle mayo, lettuce, tomato.', fr: 'Oven-roasted chicken, guacamole, Monetary jack cheese, chipotle mayo, lettuce, tomato.' },
        price: '$18.99',
      },
      {
        id: 'classic-club',
        title: { en: 'Classic Club', fr: 'Classic Club' },
        body: { en: 'Oven roasted chicken breast, bacon, cheddar cheese, fresh lettuce, tomato & dripping with mayo.', fr: 'Oven roasted chicken breast, bacon, cheddar cheese, fresh lettuce, tomato & dripping with mayo.' },
        price: '$18.99',
      },
      {
        id: 'the-diner-club',
        title: { en: 'The Diner Club', fr: 'The Diner Club' },
        body: { en: '2 Over-medium eggs, crispy breaded chicken breast, ham, bacon, cheddar, mayo, lettuce, tomato.', fr: '2 Over-medium eggs, crispy breaded chicken breast, ham, bacon, cheddar, mayo, lettuce, tomato.' },
        price: '$19.99',
      },
      {
        id: 'the-rick-rueben',
        title: { en: 'The Rick Rueben', fr: 'The Rick Rueben' },
        body: { en: 'Stacked, juicy, thin-sliced Montreal style smoked meat with sauerkraut, swiss cheese & 1000 Island dressing on grilled rye. * Served as is, no alterations accepted.', fr: 'Stacked, juicy, thin-sliced Montreal style smoked meat with sauerkraut, swiss cheese & 1000 Island dressing on grilled rye. * Served as is, no alterations accepted.' },
        price: '$18.49',
      },
      {
        id: 'hog-wild',
        title: { en: 'Hog Wild', fr: 'Hog Wild' },
        body: { en: 'Slow roasted pulled pork smothered in BBQ sauce, caramelized onions, topped with cheddar cheese, homemade slaw & chipotle mayo on a brioche bun. Napkins will be required.', fr: 'Slow roasted pulled pork smothered in BBQ sauce, caramelized onions, topped with cheddar cheese, homemade slaw & chipotle mayo on a brioche bun. Napkins will be required.' },
        price: '$18.49',
      },
      {
        id: 'crispy-chicken-caesar-salad-wrap',
        title: { en: 'Crispy Chicken Caesar Salad Wrap', fr: 'Crispy Chicken Caesar Salad Wrap' },
        body: { en: 'Sink your teeth into this hearty wrap, where juicy, crispy fried chicken meets the perfect crunch of a classic Caesar salad. Tossed in creamy Caesar dressing, topped with smoky bacon, and finished with a generous sprinkle of Parmesan cheese, all wrapped snugly in a warm, soft tortilla. A bold twist on a diner favorite—wrapped and ready to savor!', fr: 'Sink your teeth into this hearty wrap, where juicy, crispy fried chicken meets the perfect crunch of a classic Caesar salad. Tossed in creamy Caesar dressing, topped with smoky bacon, and finished with a generous sprinkle of Parmesan cheese, all wrapped snugly in a warm, soft tortilla. A bold twist on a diner favorite—wrapped and ready to savor!' },
        price: '$18.99',
      },
      {
        id: 'buffalo-chicken-wrap',
        title: { en: 'Buffalo Chicken Wrap', fr: 'Buffalo Chicken Wrap' },
        body: { en: 'Crispy chicken tenders tossed in Frank\'s Red Hot sauce & creamy ranch dressing, paired with Monterey jack cheese, lettuce, & tomato.', fr: 'Crispy chicken tenders tossed in Frank\'s Red Hot sauce & creamy ranch dressing, paired with Monterey jack cheese, lettuce, & tomato.' },
        price: '$18.49',
      },
      {
        id: 'veggie-wrap',
        title: { en: 'Veggie Wrap', fr: 'Veggie Wrap' },
        body: { en: 'Guacamole, mixed peppers, onions, carrots, cucumbers, lettuce, feta cheese, & pesto mayo.', fr: 'Guacamole, mixed peppers, onions, carrots, cucumbers, lettuce, feta cheese, & pesto mayo.' },
        price: '$17.99',
      },
      {
        id: 'mean-green-club',
        title: { en: 'Mean Green Club', fr: 'Mean Green Club' },
        body: { en: 'Triple decker with guacamole, cucumber, mixed peppers, onions, lettuce, tomato, shredded carrot, cheddar, and pesto mayo.', fr: 'Triple decker with guacamole, cucumber, mixed peppers, onions, lettuce, tomato, shredded carrot, cheddar, and pesto mayo.' },
        price: '$17.99',
      },
    ],
  },
  {
    id: 'kids-menu',
    title: { en: 'Kids Menu', fr: 'Kids Menu' },
    items: [
      {
        id: 'dino-buddies',
        title: { en: 'Dino Buddies', fr: 'Dino Buddies' },
        body: { en: '5 Dino shaped chicken nuggets. Served with plum sauce, & fries or apple wedges.', fr: '5 Dino shaped chicken nuggets. Served with plum sauce, & fries or apple wedges.' },
        price: '$8.99',
      },
      {
        id: 'grilled-cheese',
        title: { en: 'Grilled Cheese', fr: 'Grilled Cheese' },
        body: { en: 'Classic grilled cheese on white bread. Served with fries or apple wedges.', fr: 'Classic grilled cheese on white bread. Served with fries or apple wedges.' },
        price: '$8.99',
      },
      {
        id: 'fish-sticks',
        title: { en: 'Fish Sticks', fr: 'Fish Sticks' },
        body: { en: 'Classic fish sticks & fries, also available with apple wedges. Served with tartar sauce.', fr: 'Classic fish sticks & fries, also available with apple wedges. Served with tartar sauce.' },
        price: '$8.99',
      },
      {
        id: 'kids-french-toast',
        title: { en: 'Kids French Toast', fr: 'Kids French Toast' },
        body: { en: 'Single slice of Brioche French toast topped lightly with icing sugar. Served with 2 strips of bacon, ham, or sausage. Apple wedges & homies also available.', fr: 'Single slice of Brioche French toast topped lightly with icing sugar. Served with 2 strips of bacon, ham, or sausage. Apple wedges & homies also available.' },
        price: '$8.99',
      },
      {
        id: 'kids-pancakes',
        title: { en: 'Kids Pancakes', fr: 'Kids Pancakes' },
        body: { en: '2 Real buttermilk pancakes topped lightly with icing sugar. Served with 2 strips of bacon, ham, or sausage. Apple wedges & homies also available.', fr: '2 Real buttermilk pancakes topped lightly with icing sugar. Served with 2 strips of bacon, ham, or sausage. Apple wedges & homies also available.' },
        price: '$8.99',
      },
      {
        id: 'kids-breakfast',
        title: { en: 'Kids Breakfast', fr: 'Kids Breakfast' },
        body: { en: '1 Egg, two pieces of meat, homies, & a slice of toast.', fr: '1 Egg, two pieces of meat, homies, & a slice of toast.' },
        price: '$8.99',
      },
      {
        id: 'kids-mac',
        title: { en: 'Kids Mac', fr: 'Kids Mac' },
        body: { en: 'A smaller portion of our classic Mama\'s mac, served with fresh fries or apple wedges.', fr: 'A smaller portion of our classic Mama\'s mac, served with fresh fries or apple wedges.' },
        price: '$8.99',
      },
      {
        id: 'kids-cheese-burger',
        title: { en: 'Kids Cheese burger', fr: 'Kids Cheese burger' },
        body: { en: 'a smaller take on the classic cheese burger. Served with fries or apples wedges.', fr: 'a smaller take on the classic cheese burger. Served with fries or apples wedges.' },
        price: '$8.99',
      },
    ],
  },
] as const;

export function dish(id: string) {
  for (const section of menu) {
    for (const item of section.items) {
      if (item.id === id) return item;
    }
  }
  throw new Error(`Unknown dish: ${id}`);
}
